{% set name = "pytest-flake8" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 69938811c51149b197c3eb8d490d9c43faceae50b2bc6f789707c1e5bf10d0de

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - flake8 >=4.0
    - pytest >=7.0

test:
  imports:
    - pytest_flake8
  commands:
    - pytest --flake8 --help

about:
  home: https://github.com/tholo/pytest-flake8
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: pytest plugin to check FLAKE8 requirements

extra:
  recipe-maintainers:
    - kynan
    - dopplershift
