{% set name = "pytest-flake8" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 358d449ca06b80dbadcb43506cd3e38685d273b4968ac825da871bd4cc436202

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.5
    - setuptools
    - pip
  run:
    - python >=3.5
    - setuptools
    - flake8 >=3.5
    - pytest >=3.5

test:
  imports:
    - pytest_flake8
  commands:
    - pytest --flake8 --help

about:
  home: https://github.com/tholo/pytest-flake8
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: pytest plugin to check FLAKE8 requirements

extra:
  recipe-maintainers:
    - kynan
    - dopplershift
