{% set name = "pytest-flake8" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 88fb35562ce32d915c6ba41ef0d5e1cfcdd8ff884a32b7d46aa99fc77a3d1fe6

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.2
    - setuptools_scm >=3.4.1
    - pip
  run:
    - python >={{ python_min }}
    - flake8 >=4.0
    - pytest >=7.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - pytest_flake8
  commands:
    - pytest --flake8 --help

about:
  home: https://github.com/coherent-oss/pytest-flake8
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: pytest plugin to check FLAKE8 requirements

extra:
  recipe-maintainers:
    - kynan
    - dopplershift
